config/routes.rb
Rails.application.routes.draw do
  root 'ideas#index'
  resources :ideas
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :idea
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user
  has_many :pledges
  has_many :votes
  has_many :comments
end

app/models/pledge.rb
class Pledge < ApplicationRecord
  belongs_to :user
  belongs_to :idea
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pledges
  has_many :ideas
  has_many :votes
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :idea
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname, :dob, :bio, :picture])
        devise_parameter_sanitizer.permit(:account_update, keys: [:fullname, :dob, :bio, :picture])
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy, :new]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = current_user.ideas.new(idea_params)
    
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    if current_user == @idea.user
      respond_to do |format|
        if @idea.update(idea_params)
          format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
          format.json { render :show, status: :ok, location: @idea }
        else
          format.html { render :edit }
          format.json { render json: @idea.errors, status: :unprocessable_entity }
        end
      end
    else
      format.html { redirect_to @idea, notice: 'You can not edit someone elses idea.' }
      format.json { render json: @idea.errors, status: :unauthorize }
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    if current_user == @idea.user
      @idea.destroy
      respond_to do |format|
        format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      format.html { redirect_to @idea, notice: 'You can not delete an someones elses idea.' }
      format.json { render json: @idea.errors, status: :unauthorize }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_params
      params.require(:idea).permit(:title, :description, :resources, :inspiration, :image, :user_id)
    end
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :resources %>
    <%= form.text_field :resources %>
  </div>

  <div class="field">
    <%= form.label :inspiration %>
    <%= form.text_area :inspiration %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Resources</th>
      <th>Inspiration</th>
      <th>Image</th>
      <th>creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.title %></td>
        <td><%= idea.description %></td>
        <td><%= idea.resources %></td>
        <td><%= idea.inspiration %></td>
        <td><%= idea.image %></td>
        <td><%= idea.user.fullname %></td>
        <td><%= link_to 'Show', idea %></td>
        <% if current_user && current_user == idea.user%>
          <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
          <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Resources:</strong>
  <%= @idea.resources %>
</p>

<p>
  <strong>Inspiration:</strong>
  <%= @idea.inspiration %>
</p>

<p>
  <strong>Image:</strong>
  <%= @idea.image %>
</p>

<p>
  <strong>Creator:</strong>
  <%= @idea.user.fullname %>
</p>

<% if current_user && current_user == @idea.user%>
  <%= link_to 'Destroy', @idea, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <%= link_to 'Edit', edit_idea_path(@idea) %> |
<% end %>

<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBucket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>